-- Minimal schema for the frontend hook (public.health_readings)
-- Run this in Supabase SQL editor.

create table if not exists public.health_readings (
  id bigint generated by default as identity primary key,
  patient_id text,
  device_id text,
  temperature double precision,
  heart_rate integer,
  blood_oxygen integer,
  activity_level double precision,
  fall_detected boolean default false,
  event_type text,
  event_message text,
  event_time timestamptz,
  latitude double precision,
  longitude double precision,
  location_source text,
  location_synced_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.health_readings add column if not exists device_id text;
alter table public.health_readings add column if not exists fall_detected boolean default false;
alter table public.health_readings add column if not exists event_type text;
alter table public.health_readings add column if not exists event_message text;
alter table public.health_readings add column if not exists event_time timestamptz;
alter table public.health_readings add column if not exists latitude double precision;
alter table public.health_readings add column if not exists longitude double precision;
alter table public.health_readings add column if not exists location_source text;
alter table public.health_readings add column if not exists location_synced_at timestamptz;

create index if not exists health_readings_patient_id_created_at_idx
  on public.health_readings (patient_id, created_at desc);

alter table public.health_readings enable row level security;

-- For quick testing only (public read). Tighten for production.
create policy "health_readings_select_public"
  on public.health_readings
  for select
  to anon
  using (true);

-- Allow inserts from anon for quick testing (OPTIONAL). Remove in production.
create policy "health_readings_insert_public"
  on public.health_readings
  for insert
  to anon
  with check (true);

-- Required if the browser app writes the captured fall location
-- back into the same row after geolocation is granted.
create policy "health_readings_update_public"
  on public.health_readings
  for update
  to anon
  using (true)
  with check (true);
