-- Minimal schema for the frontend hook (public.health_readings)
-- Run this in Supabase SQL editor.

create table if not exists public.health_readings (
  id bigint generated by default as identity primary key,
  patient_id text,
  temperature double precision,
  heart_rate integer,
  blood_oxygen integer,
  activity_level double precision,
  fall_detected boolean default false,
  latitude double precision,
  longitude double precision,
  created_at timestamptz not null default now()
);

create index if not exists health_readings_patient_id_created_at_idx
  on public.health_readings (patient_id, created_at desc);

alter table public.health_readings enable row level security;

-- For quick testing only (public read). Tighten for production.
create policy "health_readings_select_public"
  on public.health_readings
  for select
  to anon
  using (true);

-- Allow inserts from anon for quick testing (OPTIONAL). Remove in production.
create policy "health_readings_insert_public"
  on public.health_readings
  for insert
  to anon
  with check (true);
