-- Schema for ESP32 -> Supabase -> React realtime dashboard.
-- Run this in the Supabase SQL editor.

create table if not exists public.health_data (
  id bigint generated by default as identity primary key,
  patient_id text,
  device_id text,
  temperature double precision,
  heart_rate integer,
  spo2 integer,
  acceleration double precision,
  fall_detected boolean default false,
  latitude double precision,
  longitude double precision,
  device_timestamp_ms bigint,
  created_at timestamptz not null default now()
);

create index if not exists health_data_patient_id_created_at_idx
  on public.health_data (patient_id, created_at desc);

create index if not exists health_data_device_id_created_at_idx
  on public.health_data (device_id, created_at desc);

alter table public.health_data enable row level security;

create policy "health_data_select_public"
  on public.health_data
  for select
  to anon
  using (true);

create policy "health_data_insert_public"
  on public.health_data
  for insert
  to anon
  with check (true);
