-- Minimal schema + policies for the current live table (public.health_data)
-- Run this in Supabase SQL editor if your .env points to VITE_SUPABASE_HEALTH_TABLE=health_data.

create table if not exists public.health_data (
  id bigint generated by default as identity primary key,
  patient_id text,
  device_id text,
  heart_rate integer,
  spo2 integer,
  fall_detected boolean default false,
  acceleration double precision,
  temperature double precision,
  latitude double precision default 0,
  longitude double precision default 0,
  gps_accuracy double precision default 0,
  location_timestamp bigint default 0,
  device_timestamp_ms bigint,
  created_at timestamptz not null default now()
);

alter table public.health_data add column if not exists patient_id text;
alter table public.health_data add column if not exists device_id text;
alter table public.health_data add column if not exists heart_rate integer;
alter table public.health_data add column if not exists spo2 integer;
alter table public.health_data add column if not exists fall_detected boolean default false;
alter table public.health_data add column if not exists acceleration double precision;
alter table public.health_data add column if not exists temperature double precision;
alter table public.health_data add column if not exists latitude double precision default 0;
alter table public.health_data add column if not exists longitude double precision default 0;
alter table public.health_data add column if not exists gps_accuracy double precision default 0;
alter table public.health_data add column if not exists location_timestamp bigint default 0;
alter table public.health_data add column if not exists device_timestamp_ms bigint;
alter table public.health_data add column if not exists created_at timestamptz not null default now();

create index if not exists health_data_patient_id_created_at_idx
  on public.health_data (patient_id, created_at desc);

alter table public.health_data enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'health_data'
  ) then
    execute 'alter publication supabase_realtime add table public.health_data';
  end if;
end
$$;

drop policy if exists "health_data_select_public" on public.health_data;
create policy "health_data_select_public"
  on public.health_data
  for select
  to anon
  using (true);

drop policy if exists "health_data_insert_public" on public.health_data;
create policy "health_data_insert_public"
  on public.health_data
  for insert
  to anon
  with check (true);

drop policy if exists "health_data_update_public" on public.health_data;
create policy "health_data_update_public"
  on public.health_data
  for update
  to anon
  using (true)
  with check (true);
